import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-black text-zinc-100">
        <header className="fixed inset-x-0 top-0 z-20 border-b border-white/10 bg-zinc-950/85 backdrop-blur-sm">
          <div className="flex h-20 w-full items-center px-3 md:px-5">
            <div className="flex items-center">
              <a
                href="#"
                className="shrink-0 text-lg font-semibold uppercase tracking-[0.24em] text-zinc-100 transition-colors hover:text-white"
              >
                ERIC LIN
              </a>

              <span className="mx-5 hidden h-6 w-px bg-white/25 lg:block" />

              <nav className="hidden items-center gap-0 text-xs font-semibold uppercase tracking-[0.16em] text-zinc-300 lg:flex">
                <a href="#" className="px-5 transition-colors hover:text-white">
                  About
                </a>

                <span className="h-4 w-px bg-white/20" />
                <a href="#" className="px-5 transition-colors hover:text-white">
                  My Goal
                </a>
              </nav>
            </div>

            <span className="mx-5 hidden h-6 w-px bg-white/25 md:block" />

            <div className="ml-auto flex items-center gap-5 text-xs font-semibold uppercase tracking-[0.14em] text-zinc-300">
              <button type="button" className="hidden text-red-500 md:block">
                Night Mode [+]
              </button>

              <button
                type="button"
                className="hidden items-center gap-2 border border-zinc-700 bg-zinc-800 px-3 py-2 text-[0.7rem] font-bold uppercase tracking-[0.18em] text-zinc-100 transition-colors hover:bg-zinc-700 md:inline-flex"
              >
                Contact
                <span className="inline-flex h-4 w-4 items-center justify-center border border-zinc-600 bg-zinc-700 text-[0.55rem] leading-none text-zinc-200">
                  {"\u2197"}
                </span>
              </button>
            </div>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
